spring:
  datasource:
    url: jdbc:mysql://192.168.137.128:3306/db_test
    username: root
    password: rR@2019.

mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml


